### ISSUE TITLE
hc sandbox check for holochain startup is flawed and leads to misleading error

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#2390]
Issue: 
Trying to run `hc sandbox generate`, and it's failing.
Visible error message about "Failed to get admin port from conductor: RecvError(())" is misleading. That is only a symptom and quite unrelated to the cause. 

The command: 
```
hc sandbox generate workdir/todo.happ
```

This is how the log looks:
```
hc-sandbox: Creating 1 conductor sandboxes with same settings
# passphrase>

# lair-keystore init generating secure config...

# lair-keystore init config:
"/private/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc/keystore/lair-keystore-config.yaml"

# lair-keystore init connection_url:
unix:///private/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc/keystore/socket?k=eMouNPeZ77xgZewUYPXHDr50BaoJ_r1tR_M-hn_2NyY
hc-sandbox: Config ConductorConfig { tracing_override: None, environment_path: DatabaseRootPath("/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc"), keystore: LairServer { connection_url: Url2 { url: "unix:///private/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc/keystore/socket?k=eMouNPeZ77xgZewUYPXHDr50BaoJ_r1tR_M-hn_2NyY" } }, dpki: None, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 0 } }]), network: None, chc_namespace: None, db_sync_strategy: Fast }
hc-sandbox: Created directory at: /var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc Keep this path to rerun the same sandbox
hc-sandbox: Created config at /var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc/conductor-config.yaml
hc-sandbox: Command { std: "lair-keystore" "--lair-root" "/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc/keystore" "server" "--piped", kill_on_drop: true }
# lair-keystore connection_url # unix:///private/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/csTm8Gh-ZGBCiWChdp9Jc/keystore/socket?k=eMouNPeZ77xgZewUYPXHDr50BaoJ_r1tR_M-hn_2NyY #
# lair-keystore running #
WARNING: running without local db encryption
WARNING: running without local db encryption
Well, this is embarrassing.

holochain had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/report-a0ca8928-a4e3-40bb-ae59-3aab97ff5921.toml". Submit an issue or email with the subject of "holochain Crash Report" and include the report as an attachment.

- Homepage: https://github.com/holochain/holochain
- Authors: Holochain Core Dev Team <devcore@holochain.org>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
thread 'main' panicked at 'Failed to get admin port from conductor: RecvError(())', /Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain_cli_sandbox-0.2.0/src/run.rs:102:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Then, what is inside the crash report file:
running `cat /var/folders/2y/ydm_32156jn_t6lm4vymkt6w0000gn/T/report-a0ca8928-a4e3-40bb-ae59-3aab97ff5921.toml` yielded
```
name = "holochain"
operating_system = "Mac OS 13.3.1 [64-bit]"
crate_version = "0.2.1-beta-dev.0"
explanation = """
Panic occurred in file '/Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain-0.2.1-beta-dev.0/src/bin/holochain/main.rs' at line 178
"""
cause = "Could not initialize Conductor from configuration: Other({\"error\":\"Invalid lair server version, this client requires '0.2.4', but got '0.2.3'.\"})"
method = "Panic"
backtrace = """

   0: 0x104462ed0 - core::panicking::panic_fmt::h8c7f3d540a75578f
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65
   1: 0x1028f24b4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8d1261478ae38102
   2: 0x1025c93e4 - tokio::runtime::park::CachedParkThread::block_on::hb8465c6fd6d8dbf7
   3: 0x1026b33cc - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h224ba1ee7b49c3fe
   4: 0x10255e794 - tokio::runtime::runtime::Runtime::block_on::h71358f8595a6ad20
   5: 0x1026551f0 - tokio::runtime::scheduler::multi_thread::worker::block_in_place::h3d5e478a6c9d3dd4
   6: 0x1027a4c50 - holochain_util::tokio_helper::block_forever_on::h0c6017654a21a580
   7: 0x1027968d0 - holochain::main::h31c76152a949360e
   8: 0x102615e20 - std::sys_common::backtrace::__rust_begin_short_backtrace::h842de789682ad495
   9: 0x102776734 - std::rt::lang_start::{{closure}}::hcce412311b6b1144
  10: 0x10438db54 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha4b10a239e2af884
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:286
                 - std::panicking::try::do_call::h6b4bcb7d3635e86a
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483
                 - std::panicking::try::h579c8cca81ff0f69
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447
                 - std::panic::catch_unwind::h4a997c12755a6e33
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137
                 - std::rt::lang_start_internal::{{closure}}::hf20057b44f57f87c
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148
                 - std::panicking::try::do_call::hdfca34da16d8863f
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483
                 - std::panicking::try::h4f4022e500de0807
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447
                 - std::panic::catch_unwind::h62721286166676e8
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137
                 - std::rt::lang_start_internal::h659a783147314d97
                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148
  11: 0x102797078 - _main"""
```

At this point we can see that the real issue is a lair version mismatch. 

Steps to reproduce:
Install lair version 0.2.3
Install hc and holochain, version 0.2.1-beta-dev.0
Run `hc sandbox generate some-happ-file.happ`

This source code tells a story, as there's a TODO in the code there. 
https://github.com/holochain/holochain/blob/adb4efe8e621dd1d4aecf1c0ec8a658cd0777205/crates/hc_sandbox/src/run.rs#L204-L211

and this is where the error gets misreported:
https://github.com/holochain/holochain/blob/adb4efe8e621dd1d4aecf1c0ec8a658cd0777205/crates/hc_sandbox/src/run.rs#L109-L111

**Comment by ThetaSinner** [comment]
I agree this should be improved and it's not a big change. Using the same steps to reproduce, you will now see this instead

![Screenshot 2023-05-22 210119](https://github.com/holochain/holochain/assets/6267702/94365165-7ac1-46b3-b4d6-6cf98e001759)

You do still have to check the dumped report. That's `holochain` behaviour. If you'd rather see the output inline you can set `RUST_BACKTRACE` like `RUST_BACKTRACE=1 hc sandbox generate --run=0` and you will instead see


![Screenshot 2023-05-22 210617](https://github.com/holochain/holochain/assets/6267702/a46ea027-a8ab-42cd-bd70-ee1deed8403b)

**Comment by Connoropolous** [comment]
sweet!

**Comment by maackle** [comment]
What a great bug report!

**Comment by ThetaSinner** [comment]
0.2.1 has now released, closing
