### ISSUE TITLE
Corner-case failure running `cargo test` on develop

### ISSUE THREAD

**Issue by mjbrisebois** [holochain/holochain#280]
Ran on develop (commit e773d6dd619904a870fa91f874f59cd31f2225c4)

This issue is more of an FYI because the tests passed on subsequent runs.  Since random failures are hard to reproduce, I thought it would be important to capture this one.

```
test core::ribosome::host_fn::remove_link::slow_tests::ribosome_remove_link_add_remove ... ok

failures:

---- core::ribosome::guest_callback::migrate_agent::slow_tests::test_migrate_agent_multi_implemented_fail stdout ----
FATAL PANIC PanicInfo {
    payload: Any,
    message: Some(
        index 184320 out of range for slice of length 6317,
    ),  
    location: Location {
        file: "/rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/slice/mod.rs",
        line: 1034,
        col: 11,
    },  
}   
thread 'core::ribosome::guest_callback::migrate_agent::slow_tests::test_migrate_agent_multi_implemented_fail' panicked at 'index 184320 out of range for slice of length 6317', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/slice/mod.rs:1034:11
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/io/mod.rs:1504
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1022
  12: <holochain_state::env::ENVIRONMENTS as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}
             at crates/state/src/env.rs:41
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  14: rust_begin_unwind
             at src/libstd/panicking.rs:419
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  16: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2751
  17: <serde_bytes::bytebuf::ByteBuf as serde::de::Deserialize>::deserialize
  18: <wasmer_runtime_core::sys::<impl serde::de::Deserialize for wasmer_runtime_core::sys::unix::memory::Memory>::deserialize::MemoryVisitor as serde::de::Visitor>::visit_seq
  19: wasmer_runtime_core::cache::_IMPL_DESERIALIZE_FOR_ArtifactInner::<impl serde::de::Deserialize for wasmer_runtime_core::cache::ArtifactInner>::deserialize
  20: wasmer_runtime_core::cache::Artifact::deserialize
  21: <wasmer_runtime::cache::FileSystemCache as wasmer_runtime::cache::Cache>::load_with_backend
  22: <holochain_wasmer_host::memory_cache::MemoryFallbackFileSystemCache as wasmer_runtime::cache::Cache>::load_with_backend
  23: <holochain_wasmer_host::memory_cache::MemoryFallbackFileSystemCache as wasmer_runtime::cache::Cache>::load
  24: holochain_wasmer_host::instantiate::module
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain_wasmer_host-0.0.40/src/instantiate.rs:21
  25: holochain::core::ribosome::wasm_ribosome::WasmRibosome::module
             at crates/holochain/src/core/ribosome/wasm_ribosome.rs:102
  26: <holochain::fixt::WasmRibosomeFixturator<holochain::fixt::curve::Zomes> as core::iter::traits::iterator::Iterator>::next
             at crates/holochain/src/fixt.rs:81
  27: holochain::core::ribosome::guest_callback::migrate_agent::slow_tests::test_migrate_agent_multi_implemented_fail::{{closure}}
             at crates/holochain/src/core/ribosome/guest_callback/migrate_agent.rs:314
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/mod.rs:66
  29: tokio::runtime::enter::Enter::block_on::{{closure}}
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  30: tokio::coop::with_budget::{{closure}}
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  31: std::thread::local::LocalKey<T>::try_with
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/local.rs:263
  32: std::thread::local::LocalKey<T>::with
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/local.rs:239
  33: tokio::coop::with_budget
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  34: tokio::coop::budget
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  35: tokio::runtime::enter::Enter::block_on
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  36: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/mod.rs:82
  37: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:446
  38: tokio::runtime::context::enter   
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  39: tokio::runtime::handle::Handle::enter
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  40: tokio::runtime::Runtime::block_on
             at /home/matthew/projects/holochain-2020/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  41: holochain::core::ribosome::guest_callback::migrate_agent::slow_tests::test_migrate_agent_multi_implemented_fail
             at crates/holochain/src/core/ribosome/guest_callback/migrate_agent.rs:309
  42: holochain::core::ribosome::guest_callback::migrate_agent::slow_tests::test_migrate_agent_multi_implemented_fail::{{closure}}
             at crates/holochain/src/core/ribosome/guest_callback/migrate_agent.rs:309
  43: core::ops::function::FnOnce::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
  44: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  45: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  46: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  47: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  48: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  49: test::run_test_in_process
             at src/libtest/lib.rs:541 
  50: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450 
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    core::ribosome::guest_callback::migrate_agent::slow_tests::test_migrate_agent_multi_implemented_fail

test result: FAILED. 170 passed; 1 failed; 18 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p holochain --lib'
```

cc @maackle

**Comment by thedavidmeister** [comment]
@freesig i think this was just stale wasm compilation wasn't it?

**Comment by freesig** [comment]
oh yeh it could be. 
You might need to do `cargo test warm_wasm_tests --manifest-path=crates/holochain/Cargo.toml --features slow_tests,build_wasms` first
