### ISSUE TITLE
[BUG] Holochain v0.3.0-beta-dev.46 and later fail to reach consistency in app validation

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#3660]
**Describe the bug**

Some sweettests of normal scaffolded apps fail with holochain v0.3.0-beta-dev.46, with awaiting consistency errors, even when waiting for 60 seconds.

This is the logs I get:

```
❯ RUST_LOG=holochain::core::workflow=info DNA_PATH=../../../workdir/posts_test.dna cargo nextest run -j 1 --cargo-profile release
+ command cargo nextest run -j 1 --cargo-profile release
    Finished release [optimized] target(s) in 0.17s
    Starting 17 tests across 10 binaries (run ID: 4c26be29-5ca0-402f-b803-c3795de061c5, nextest profile: default)
        PASS [   2.941s] posts::all_posts create_a_post_and_get_all_posts
        PASS [   2.918s] posts::all_posts_entry_hash create_a_post_and_get_all_posts_entry_hash
        SLOW [> 60.000s] posts::certificate create_and_read_certificate
        FAIL [  61.961s] posts::certificate create_and_read_certificate

--- STDOUT:              posts::certificate create_and_read_certificate ---

running 1 test
Fixturator seed: 11264340770772231905
test create_and_read_certificate has been running for over 60 seconds
test create_and_read_certificate ... FAILED

failures:

failures:
    create_and_read_certificate

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 61.92s


--- STDERR:              posts::certificate create_and_read_certificate ---
2024-04-17T16:33:09.509657Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 7 ops
2024-04-17T16:33:09.511636Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 7/7 ops
2024-04-17T16:33:09.527406Z  INFO test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAkpDkOgh22lF3kHWUuvzqA6cYnkRkZ1_03kwtDTcjx4X7ULMn9)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 7 ops
2024-04-17T16:33:09.529258Z  INFO test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAkpDkOgh22lF3kHWUuvzqA6cYnkRkZ1_03kwtDTcjx4X7ULMn9)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 7/7 ops
2024-04-17T16:33:10.264770Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 17 ops
2024-04-17T16:33:10.269998Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 17/17 ops
2024-04-17T16:33:10.286106Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 9 ops
2024-04-17T16:33:10.288538Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 9/9 ops
2024-04-17T16:33:10.541199Z  WARN test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:app_validation_workflow{dna_hash=DnaHash(uhC0kJJ_Hzx2_dpQHwbNMFgXob27L27xKRXKv2R0yahK1Dg4fhcs-)}:write_async:spawn_blocking:execute_in_exclusive_rw_txn: holochain::core::workflow::app_validation_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/app_validation_workflow.rs:202: msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCkkQhGEMbi5mB5yJRsx3Gj3zcfdlEG0_WMUS8koZvHk1rrTZDM1)])
2024-04-17T16:33:10.579047Z  WARN test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:app_validation_workflow{dna_hash=DnaHash(uhC0kJJ_Hzx2_dpQHwbNMFgXob27L27xKRXKv2R0yahK1Dg4fhcs-)}:write_async:spawn_blocking:execute_in_exclusive_rw_txn: holochain::core::workflow::app_validation_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/app_validation_workflow.rs:202: msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCkkrF7vOBQ_Fv3-IY-nhKY0G0Ne-MOKuovxBqde1jlq_XO4P6MC)])
2024-04-17T16:33:10.579080Z  WARN test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:app_validation_workflow{dna_hash=DnaHash(uhC0kJJ_Hzx2_dpQHwbNMFgXob27L27xKRXKv2R0yahK1Dg4fhcs-)}:write_async:spawn_blocking:execute_in_exclusive_rw_txn: holochain::core::workflow::app_validation_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/app_validation_workflow.rs:202: msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCkkrF7vOBQ_Fv3-IY-nhKY0G0Ne-MOKuovxBqde1jlq_XO4P6MC)])
FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Timed out waiting for consistency: Consistency not achieved after 60s. Expected 40 ops, but only 38 integrated. Unintegrated ops:

        author                                                 seq  op_type (action_type)
        uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  10  StoreRecord (CreateLink)
        uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  11  StoreRecord (CreateLink)

        IntegrationStateDump { validation_limbo: 2, integration_limbo: 0, integrated: 38 },
    ),
    location: Location {
        file: "zomes/coordinator/posts/tests/certificate.rs",
        line: 68,
        col: 10,
    },
    can_unwind: true,
    force_no_backtrace: false,
}
thread 'create_and_read_certificate' panicked at zomes/coordinator/posts/tests/certificate.rs:68:10:
Timed out waiting for consistency: Consistency not achieved after 60s. Expected 40 ops, but only 38 integrated. Unintegrated ops:

author                                                 seq  op_type (action_type)
uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  10  StoreRecord (CreateLink)
uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  11  StoreRecord (CreateLink)

IntegrationStateDump { validation_limbo: 2, integration_limbo: 0, integrated: 38 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure
        PASS [   1.943s] posts::certificate create_certificate_test
------------
     Summary [  69.763s] 4/17 tests run: 3 passed, 1 failed, 0 skipped
        FAIL [  61.961s] posts::certificate create_and_read_certificate
error: test run failed

```

**Expected behavior**

Sweettest works well.

**Comment by jost-s** [comment]
I can't even get the reproduction set up:

```sh
$ nix build .#posts_test_dna -o workdir/posts_test.dna
RUST_LOG=holochain::core::workflow=info DNA_PATH=../../../workdir/posts_test.dna cargo test --profile release
warning: Git tree '/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction' is dirty
error: a 'x86_64-linux' with features {} is required to build '/nix/store/rpj3p6n8l195wji7f0gz6by618gfr6a4-cargo-package-allocator-api2-0.2.18.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
    Finished release [optimized] target(s) in 1.22s
     Running unittests src/lib.rs (target/release/deps/posts-84cd56d71f9fc06e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/all_posts.rs (target/release/deps/all_posts-601eb34532c686cd)

running 1 test
test create_a_post_and_get_all_posts ... FAILED

failures:

---- create_a_post_and_get_all_posts stdout ----
thread 'create_a_post_and_get_all_posts' panicked at zomes/coordinator/posts/tests/all_posts.rs:20:58:
called `Result::unwrap()` on an `Err` value: MrBundleError(IoError(IoError { original: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: Some("/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction/zomes/coordinator/posts/../../../workdir/posts_test.dna"), backtrace:    0: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace
   2: backtrace::capture::Backtrace::create
   3: backtrace::capture::Backtrace::new
   4: holochain_util::ffs::io_error::IoError::new
   5: all_posts::create_a_post_and_get_all_posts::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: core::ops::function::FnOnce::call_once
  11: test::__rust_begin_short_backtrace
  12: test::run_test::{{closure}}
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: __pthread_joiner_wake
 }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    create_a_post_and_get_all_posts

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.35s

error: test failed, to rerun pass `-p posts --test all_posts`


$ npm run build:happ

> build:happ
> nix build -L .#posts_test_app.meta.debug -o workdir/posts_test-debug.happ

warning: Git tree '/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction' is dirty
rust-minimal> nullglob          on
error: a 'x86_64-linux' with features {} is required to build '/nix/store/rpj3p6n8l195wji7f0gz6by618gfr6a4-cargo-package-allocator-api2-0.2.18.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```

**Comment by jost-s** [comment]
If you provide the sweettest file and the coordinator and integrity, I can look at the validation problem.

**Comment by guillemcordoba** [comment]
Oh right sorry! I just updated the readme with correct instructions, could you try again?

**Comment by jost-s** [comment]
Sure. The same is happening:
```sh
$ nix build .#posts_test_dna.meta.debug -o workdir/posts_test.dna
RUST_LOG=holochain::core::workflow=info DNA_PATH=../../../workdir/posts_test.dna cargo test --profile release
warning: Git tree '/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction' is dirty
warning: updating lock file '/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction/flake.lock':
• Updated input 'scaffolding/holochain/versions':
    'github:holochain/holochain/86849cbe111a7fd8a00f63a6a16e4139c6bbbb07?dir=versions/weekly' (2024-04-23)
  → 'github:holochain/holochain/52bffa085f579ce8de86b1c33777769e87e8be14?dir=versions/weekly' (2024-04-23)
warning: Git tree '/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction' is dirty
error: a 'x86_64-linux' with features {} is required to build '/nix/store/05kssdf3w6i627maf4pr2fhpnik1lg1q-rust-minimal-1.75.0.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
    Finished release [optimized] target(s) in 1.20s
     Running unittests src/lib.rs (target/release/deps/posts-84cd56d71f9fc06e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/all_posts.rs (target/release/deps/all_posts-601eb34532c686cd)

running 1 test
test create_a_post_and_get_all_posts ... FAILED

failures:

---- create_a_post_and_get_all_posts stdout ----
thread 'create_a_post_and_get_all_posts' panicked at zomes/coordinator/posts/tests/all_posts.rs:20:58:
called `Result::unwrap()` on an `Err` value: MrBundleError(IoError(IoError { original: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: Some("/Users/jost/Desktop/holochain/scaffolded-tryorama/sweettest-app-validation-reproduction/zomes/coordinator/posts/../../../workdir/posts_test.dna"), backtrace:    0: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace
   2: backtrace::capture::Backtrace::create
   3: backtrace::capture::Backtrace::new
   4: holochain_util::ffs::io_error::IoError::new
   5: all_posts::create_a_post_and_get_all_posts::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: core::ops::function::FnOnce::call_once
  11: test::__rust_begin_short_backtrace
  12: test::run_test::{{closure}}
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: __pthread_joiner_wake
 }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    create_a_post_and_get_all_posts

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.13s

error: test failed, to rerun pass `-p posts --test all_posts`
```

**Comment by guillemcordoba** [comment]
Oh nice finding! You discovered a bug in the infrastructure repo, which I was able to fix just now. Can you please git pull and try again? This time I've tested the instructions on a mac myself to make sure they work.

**Comment by jost-s** [comment]
Sweet! Finally I have the reproduction. 🙏

**Comment by ThetaSinner** [comment]
I'm seeing something similar using tryorama with 0.3-48. For validation rules that were passing on 0.3-44, I now see a few warnings about failed validation with awaiting dependencies and then nothing else gets logged until the tests time out.

What's odd is that they aren't always timing out on the same dhtSync. Within the same test I see it fail at different points. So it seems like there's some flakiness too.

**Comment by jost-s** [comment]
@guillemcordoba I've dug into the problem and it happens because app validation isn't retriggered after missing dependencies have been fetched. I've narrowed the problem down to multiple ops depending on the same action hash and firing off fetch requests for it in parallel, but the internal struct that keeps track of them doesn't update correctly so that the ops that are missing those deps will be erroneously filtered out from validation.

I've tested this reproduction with Holochain v0.4.0-dev.1 and the problem doesn't occur. That's because ops are no longer validated in parallel and tracking missing hashes works correctly. Please try this again with the latest version of Holochain or v0.3.0-beta-dev.48 even.

**Comment by guillemcordoba** [comment]
As @ThetaSinner said, this still happens with HC v0.3.0-beta-dev.48, I've also tested it with the same result. I'll try with v0.4! Is the change in the validation to the sequencing model going to be in the 0.3-rc release?

**Comment by guillemcordoba** [comment]
@jost-s I just tried with hc v0.4.0-dev.1. I was able to still reproduce the issue, see https://github.com/guillemcordoba/sweettest-app-validation-reproduction/actions/runs/8983336471/job/24672874210#step:6:5593. Although it does happen much less often I think, it still happens. This issue is preventing me to upgrade to latest holochain, as I can't get the tests for any of my apps to succeed.

**Comment by jost-s** [comment]
Actually yes, I found the location of the actual bug after that. The next release could already have the fix.

**Comment by jost-s** [comment]
> As @ThetaSinner said, this still happens with HC v0.3.0-beta-dev.48, I've also tested it with the same result. I'll try with v0.4! Is the change in the validation to the sequencing model going to be in the 0.3-rc release?

At the moment it isn't part of the rc branch. I don't know if the plan is to include it.

**Comment by ThetaSinner** [comment]
@jost-s I think this is the only thing we're currently waiting on to get an RC out for 0.3 so if you could put any fixes on `develop-0.3` then we will get that released. The 0.4.0-dev.2 release should be coming out tonight so we can give that a test :)

**Comment by jost-s** [comment]
> > Is the change in the validation to the sequencing model going to be in the 0.3-rc release?
> At the moment it isn't part of the rc branch. I don't know if the plan is to include it.

@guillemcordoba Yes, I'll backport the serialization change to 0.3.

**Comment by jost-s** [comment]
The upcoming release contains the fix. Please re-open if the issue persists.

**Comment by jost-s** [comment]
The upcoming release contains the fix. Please re-open if the issue persists.

By the way the serialization change already is part of 0.3.
