### ISSUE TITLE
ongoing incomprehensible errors with wasm panics and wbindgen

### ISSUE THREAD

**Issue by nphias** [holochain/holochain#4852]
i assume this means some problem with the wasm build.. but better error handling and info is needed

mac os ventura
 "dependencies": {
    "@msgpack/msgpack": "^2.7.0",
    "@holochain/client": "^0.16.2",
    "@holochain/tryorama": "^0.15.1",
    "js-base64": "3.7.5",
    "typescript": "^4.9.4",
    "vitest": "^0.28.4"
  },

stderr | .test.ts > create and read zome
error occurred during test run: internal_error: Conductor returned an error while using a ConductorApi: RibosomeError(WasmRuntimeError(RuntimeError { source: User(WasmError { file: "crates/holochain/src/core/ribosome/real_ribosome.rs", line: 441, error: Compile("Error while importing \"__wbindgen_placeholder__\".\"__wbindgen_describe\": unknown import. Expected Function(FunctionType { params: [I32], results: [] })") }), wasm_trace: [], native_trace:    0: 
```

<unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
 }))
    at catchError (file:///Users/node_modules/@holochain/tryorama/node_modules/@holochain/client/lib/api/common.js:37:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AdminWebsocket.installApp (file:///Users/node_modules/@holochain/tryorama/node_modules/@holochain/client/lib/api/common.js:13:22)
    at Scenario.addPlayerWithApp (file:///Users/node_modules/@holochain/tryorama/lib/local/scenario.js:61:25)
    at async Promise.all (index 1)
    at Scenario.addPlayersWithApps (file:///Users/node_modules/@holochain/tryorama/lib/local/scenario.js:77:25)
    at /Users/test.ts:20:26
    at Module.runScenario (file:///Users/node_modules/@holochain/tryorama/lib/local/scenario.js:131:9)
    at /Users/test.ts:10:3
    at runTest (file:///Users/node_modules/@vitest/runner/dist/index.js:439:9)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 ❯ catchError ../node_modules/@holochain/tryorama/node_modules/@holochain/client/lib/api/common.js:37:23
 ❯ AdminWebsocket.installApp ../node_modules/@holochain/tryorama/node_modules/@holochain/client/lib/api/common.js:13:22
 ❯ Scenario.addPlayerWithApp ../node_modules/@holochain/tryorama/lib/local/scenario.js:61:25
 ❯ Scenario.addPlayersWithApps ../node_modules/@holochain/tryorama/lib/local/scenario.js:77:25
 ❯ src/my_space/schedule/appointment.test.ts:20:26
     18|     // Add 2 players with the test app to the Scenario. The returned players
     19|     // can be destructured.
     20|     const [alice, bob] = await scenario.addPlayersWithApps([appSource, appSource]);
       |                          ^
     21| 
     22|     // Shortcut peer discovery through gossip and register all agents in every
 ❯ Module.runScenario ../node_modules/@holochain/tryorama/lib/local/scenario.js:131:9


```

**Comment by mattyg** [comment]
>  moving forward to saving devs time.. if we cant get the offending cargo included crate into the error messages.

Actually I wonder if it might be possible to get the stack trace from the wasm guest. Not sure how straightforward it would be, but we can investigate. I moved this issue to the holochain repo and updated the name to reflect.

> if we cant get the offending cargo included crate into the error messages. Second best would be to have pre-wasm build analysis flag and warn/error on incompatible wasm crates.

Hmm, I'm don't think this is possible. I can't think of an automated, reliable, practical method to verify that a given crate is not making calls to system interfaces that are not available over wasm. I think we're stuck with manually reviewing crates with an understanding of what will cause wasm incompatibility, and only adding one dependency at a time to confirm it works. (See https://rustwasm.github.io/book/reference/which-crates-work-with-wasm.html#which-crates-will-work-off-the-shelf-with-webassembly)

**Comment by ThetaSinner** [comment]
I know these errors aren't perfect but we can't actually maintain crate context. The WASM was compiled from Rust into what is effectively a binary. The symbol "wbindgen_placeholder" is compiler output from the Rust compile stage. That is then being run through another compile step to create native code from the WASM and that symbol was expected to be present.

Yes it's not super clear, but if you follow that symbol through a search engine, you quickly get to https://github.com/rustwasm/wasm-bindgen. That then gives you a way in because you can just run `cargo tree -i wasm-bindgen` against your project to figure out how you imported it.

As for how that got imported, yes I can see that `holochain_trace` uses `chrono` which then has a default feature of `wasmbind`, which won't work when Holochain tries to build it. But we're back at the crux of the problem, that you can't include libraries that aren't going to run on `wasm32-unknown-unknown`. That feature is enabling JavaScript integration for `chrono`.

The `hdi` provides `tracing` and `tracing-core`, which means you can do trace logging without `holochain_trace`. There should be no need for `holochain_trace` in a WASM. If it's included through some other path that it shouldn't be then we could look at that.

I'm keen that we don't spend any more time on this issue without both a reproduction and the output of `cargo tree -i wasm-bindgen` so that we can see what the problem is that we're trying to solve.

**Comment by ThetaSinner** [comment]
Closing as we don't have a good solution to answer the request
