### ISSUE TITLE
unable to use "call" function of hc sandbox

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#713]
Terminal 1
```
hc sandbox run 0 --ports 8888

Mar 23 12:14:15.635 ERROR lair_keystore_client: error=IpcClientConnectError("/private/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/wGaAiZnsWdS4Vf98LQW5v/keystore/socket", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }) file="/Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/lair_keystore_client-0.0.1-alpha.11/src/lib.rs" line=42

Conductor ready.
hc-sandbox: Running conductor on admin port 50085
hc-sandbox: Attaching app port 8888
```

Terminal 2
```
hc sandbox call -r=50085 list-active-apps
thread 'main' panicked at 'Failed to create CmdRunner because admin port failed to connect: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })', /Users/connor/.cargo/git/checkouts/holochain-391184137afba57c/181baec/crates/hc_sandbox/src/lib.rs:159:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by robbiecarlton** [comment]
I get a very similar issue on macOS Catalina

```
hc sandbox clean
hc sandbox create
hc sandbox call new-agent
```
results in
```
Error: Failed to connect to running conductor or start one Io(Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" })
```
same is true for `hc s call add-app-ws`, `add-admin-ws`, and `list-active-apps` (I stopped checking here, so this list is not exhaustive).

These all work fine for me on linux.

**Comment by Connoropolous** [comment]
Yeah, I experience that too ^

**Comment by robbiecarlton** [comment]
Are you on a Mac @Connoropolous?

**Comment by Connoropolous** [comment]
Yeah

**Comment by Connoropolous** [comment]
Big Sur

**Comment by freesig** [comment]
I haven't tested sandbox on mac and don't personally have access to one to try it but it looks like your commands are correct. Maybe there is some issue with more then one client connecting to the same websocket port on mac? I'd be happy to pair with either of you to try and figure out what's going wrong

**Comment by freesig** [comment]
@Connoropolous I wasn't able to reproduce your issue. I did find a mac specific bug with the help of @robbiecarlton but we weren't able to reproduce the scenario even on mac. Is there any other details you have around the issue?

**Comment by Connoropolous** [comment]
Hey, I was going to try to get something more for you today, but didn't quite get there. Actually, I did one thing which was get a backtrace ...

```
RUST_BACKTRACE=full hc sandbox call -r=59218 list-active-apps
thread 'main' panicked at 'Failed to create CmdRunner because admin port failed to connect: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })', /Users/connor/.cargo/git/checkouts/holochain-391184137afba57c/181baec/crates/hc_sandbox/src/lib.rs:159:14
stack backtrace:
   0:        0x109e9e024 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
   1:        0x109ec1100 - core::fmt::write::haf3903118f694c48
   2:        0x109e96dd6 - std::io::Write::write_fmt::h7385463ac87804ed
   3:        0x109ea00cf - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
   4:        0x109e9fd9d - std::panicking::default_hook::h7bd29c87df967048
   5:        0x109ea069b - std::panicking::rust_panic_with_hook::hae2b05f08a320721
   6:        0x109ea021b - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
   7:        0x109e9e498 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
   8:        0x109ea01da - _rust_begin_unwind
   9:        0x109ee466f - core::panicking::panic_fmt::h1b194bb80d76fb10
  10:        0x109ee4575 - core::result::unwrap_failed::h56c9cad3598d6b68
  11:        0x109a91e48 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haa8a66d9f5615106
  12:        0x109a6a592 - holochain_cli_sandbox::cli::HcSandbox::run::{{closure}}::ha35377edd9755f81
  13:        0x109a8cc6e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h78c5a48b9931a752
  14:        0x109a571d6 - std::thread::local::LocalKey<T>::with::hb17ec3a3d51da771
  15:        0x109aafb69 - tokio::park::thread::CachedParkThread::block_on::ha9275e458c1bfd52
  16:        0x109a80dd9 - tokio::runtime::thread_pool::ThreadPool::block_on::h000aa13a3b8bd72c
  17:        0x109a3b6a0 - tokio::runtime::Runtime::block_on::h3f5f13c3726caefa
  18:        0x109abdb05 - hc::main::hb500473e9adfad21
  19:        0x109ad6d5a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e051c469ff17ebf
  20:        0x109accdd1 - std::rt::lang_start::{{closure}}::h6ec0000d679e7cb5
  21:        0x109ea0af4 - std::rt::lang_start_internal::hd38bb63f9540b327
  22:        0x109abdbc9 - _main
```

**Comment by Connoropolous** [comment]
Also note, I am using Holochain at this mid March commit. I wondered if switching to most recent would eliminate the bug, but I haven't tried that yet. 

https://github.com/holochain/holochain/tree/181baec40af0375a9d4e86a5953c44dc91e5cfe4

**Comment by artbrock** [comment]
Hey @Connoropolous did this get resolved for you in later versions of Holochain?  Or is this still an outstanding issue?

**Comment by Connoropolous** [comment]
I'll use latest https://github.com/holochain/holochain-dna-build-tutorial and nix-shell there to double check @artbrock thanks for asking. Will report back!

**Comment by Connoropolous** [comment]
Seems to be in working order if I use recent versions, whatever holochain-dna-build-tutorial is currently bundling in its nix-shell 👍
