### ISSUE TITLE
Tryorama 0.4.3 fails with holochain v0.0.101

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#872]
With Holochain v0.0.101 (or commit) this is the error I get when trying to run tests with tryorama 0.4.3:

```
App Port spun up on port  35243
FIXME: ignoring onJoin
09:40:06 [tryorama] info: Spawning lair for test with keystore at:  /tmp/tmp.SPAQEOhKau/tryorama/QbUM9a/keystore
09:40:06 [tryorama] info: Using conductor path:  holochain
09:40:06 [tryorama] info: Holochain version:     <Buffer 68 6f 6c 6f 63 68 61 69 6e 20 30 2e 30 2e 31 30 31 0a>
09:40:06 [tryorama] info: Conductor config path: /tmp/tmp.SPAQEOhKau/tryorama/QbUM9a/conductor-config.yml
09:40:06 info: 
☯☯☯ [[[CONDUCTOR c2]]]
☯ 
☯ ###HOLOCHAIN_SETUP###
☯ ###ADMIN_PORT:33002###
☯ ###HOLOCHAIN_SETUP_END###
☯ Conductor ready.
☯ 
09:40:06 [tryorama] info: Conductor 'c2' process spawning completed.
App Port spun up on port  36605
09:40:22 [tryorama] error: Test error: 'Error: Timed out in 15000ms: install_app\n' +
  '    at Timeout.<anonymous> (/home/guillem/projects/lightningrod/syn/node_modules/.pnpm/@holochain+conductor-api@0.0.4/node_modules/@holochain/conductor-api/src/websocket/common.ts:16:14)\n' +
  '    at listOnTimeout (internal/timers.js:554:17)\n' +
  '    at processTimers (internal/timers.js:497:7)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/home/guillem/projects/lightningrod/syn/node_modules/.pnpm/@holochain+tryorama@0.4.3/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/home/guillem/projects/lightningrod/syn/node_modules/.pnpm/tape@5.2.2/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/home/guillem/projects/lightningrod/syn/node_modules/.pnpm/tape@5.2.2/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/home/guillem/projects/lightningrod/syn/node_modules/.pnpm/tape@5.2.2/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/home/guillem/projects/lightningrod/syn/node_modules/.pnpm/tape@5.2.2/node_modules/tape/lib/test.js:91:32)
          at /home/guillem/projects/lightningrod/syn/node_modules/.pnpm/@holochain+tryorama@0.4.3/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at runNextTicks (internal/process/task_queues.js:62:5)
          at listOnTimeout (internal/timers.js:523:9)
          at processTimers (internal/timers.js:497:7)
  ...
```

Tryorama does work well Holochain's `develop` branch.

**Comment by lucksus** [comment]
I'm just trying to update to 0.0.101 and I see a lot of those timeouts in my tests - and I'm not even using tryorama. I've also updated to @holochain/conductor-api version 0.1.1. I get timeouts on `install_app` and a lot on `app_info`:
```
    console.error
      LanguageFactory: ERROR creating new language: Error: Timed out in 100000ms: app_info
          at Timeout.<anonymous> (/home/lucksus/code/perspect3vism/ad4m-executor/node_modules/@holochain/conductor-api/src/websocket/common.ts:16:14)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

```
and
```
    console.error
      Error: Timed out in 15000ms: install_app
          at Timeout.<anonymous> (/home/lucksus/code/perspect3vism/ad4m-executor/node_modules/@holochain/conductor-api/src/websocket/common.ts:16:14)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

```

**Comment by steveeJ** [comment]
a fix for this was released in https://github.com/holochain/holochain/releases/tag/holochain-0.0.103

thanks for reporting!
