### ISSUE TITLE
Flakey Test

### ISSUE THREAD

**Issue by freesig** [holochain/holochain#914]
getting a failed test that i've also seen fail locally, so i assume this is a flake.

EDIT: after restarting the CI job twice it succeeded so it's very likely not a regression introduced here.

<details>

```
test test::tests::test_gossip_transport ... thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some("agent-1-data")`,
 right: `None`', crates/kitsune_p2p/kitsune_p2p/src/test.rs:355:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/core/src/panicking.rs:143:5
   4: kitsune_p2p::test::tests::test_gossip_transport::{{closure}}
             at ./src/test.rs:355:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/park/thread.rs:263:54
   7: tokio::coop::with_budget::{{closure}}
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:106:9
   8: std::thread::local::LocalKey<T>::try_with
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
   9: std::thread::local::LocalKey<T>::with
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  10: tokio::coop::with_budget
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:99:5
  11: tokio::coop::budget
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:76:5
  12: tokio::park::thread::CachedParkThread::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/park/thread.rs:263:31
  13: tokio::runtime::enter::Enter::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/enter.rs:151:13
  14: tokio::runtime::thread_pool::ThreadPool::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/mod.rs:71:9
  15: tokio::runtime::Runtime::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/mod.rs:452:43
  16: kitsune_p2p::test::tests::test_gossip_transport
             at ./src/test.rs:361:9
  17: kitsune_p2p::test::tests::test_gossip_transport::{{closure}}
             at ./src/test.rs:299:11
  18: core::ops::function::FnOnce::call_once
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
FAILED
```
</details>

_Originally posted by @steveeJ in https://github.com/holochain/holochain/issues/911#issuecomment-895959269_

**Comment by guillemcordoba** [comment]
I have also seen this in my PRs :)

**Comment by guillemcordoba** [comment]
This one is also flakey I think: https://app.circleci.com/pipelines/github/holochain/holochain/7522/workflows/e9041fb7-012a-47e3-8e82-7a7f68203ac8/jobs/9160

**Comment by ThetaSinner** [comment]
@freesig @guillemcordoba because this issue is quite old I'm going to close it. Flaky tests aren't going away any time soon so please feel free to open new issues or PRs to fix/disable them as appropriate.

Note that the originally referenced test `test_gossip_transport` is currently marked disabled because it's flaky and because the thing it's testing is becoming less relevant.
I can't get to the test behind the CircleCI link unfortunately.
