### ISSUE TITLE
test::tests::test_gossip_transport fails (probably flaky)

### ISSUE THREAD

**Issue by steveeJ** [holochain/holochain#989]
this came up in a PR that's certainly unrelated #988 

```
test test::tests::test_gossip_transport ... thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some("agent-1-data")`,
 right: `None`', crates/kitsune_p2p/kitsune_p2p/src/test.rs:355:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at /nix/store/825kqk0fk118yqv4xa7bx4i7xpnsyixj-rust-default-1.53.0/lib/rustlib/src/rust/library/core/src/panicking.rs:143:5
   4: kitsune_p2p::test::tests::test_gossip_transport::{{closure}}
             at ./src/test.rs:355:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /nix/store/825kqk0fk118yqv4xa7bx4i7xpnsyixj-rust-default-1.53.0/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/park/thread.rs:263:54
   7: tokio::coop::with_budget::{{closure}}
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:106:9
   8: std::thread::local::LocalKey<T>::try_with
             at /nix/store/825kqk0fk118yqv4xa7bx4i7xpnsyixj-rust-default-1.53.0/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
   9: std::thread::local::LocalKey<T>::with
             at /nix/store/825kqk0fk118yqv4xa7bx4i7xpnsyixj-rust-default-1.53.0/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  10: tokio::coop::with_budget
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:99:5
  11: tokio::coop::budget
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:76:5
  12: tokio::park::thread::CachedParkThread::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/park/thread.rs:263:31
  13: tokio::runtime::enter::Enter::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/enter.rs:151:13
  14: tokio::runtime::thread_pool::ThreadPool::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/mod.rs:72:9
  15: tokio::runtime::Runtime::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/mod.rs:459:43
  16: kitsune_p2p::test::tests::test_gossip_transport
             at ./src/test.rs:361:9
  17: kitsune_p2p::test::tests::test_gossip_transport::{{closure}}
             at ./src/test.rs:299:11
  18: core::ops::function::FnOnce::call_once
             at /nix/store/825kqk0fk118yqv4xa7bx4i7xpnsyixj-rust-default-1.53.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
FAILED
```

**Comment by ThetaSinner** [comment]
Related to https://github.com/holochain/holochain/issues/914, this known to be flaky and has been disabled. The comment on the test ignore annotation suggests that it may not be worth fixing. Closing this issue for now.
